title: Crossborder Code
subtitle: Research in Global Macroeconomics and Finance
author: Matthew Potts
logo: logo.png

execute:
  execute_notebooks: off

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/matthew-potts/matthewpotts.github.io
  path_to_book: docs
  branch: master

html:
  favicon: logo.png
  use_repository_button: false
  use_hide_code_button: true
  hide_code_all: true
  theme:
    use_sidenotes: false
    toggle_switch: false

launch_buttons:
  colab_url: "" 
hide_code: true

sphinx:
  config:
    html_theme: "pydata_sphinx_theme"
    copyright: "2025"
    html_context:
      default_mode: light
